services:
  - type: web
    name: stock-dashboard-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CORS_ORIGINS
        value: https://frontend-7wa5odsvi-markying2014s-projects.vercel.app,http://localhost:3000
      - key: PORT
        value: 10000
