services:
  - type: web
    name: stock-dashboard-api
    env: python
    rootDir: backend
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CORS_ORIGINS
        value: https://frontend-7wa5odsvi-markying2014s-projects.vercel.app,http://localhost:3000
